project:
  type: website
  output-dir: docs

website:
  title: "VegVault"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: People
        href: website/people.qmd
      - text: Database
        menu:
          - text: VegVault Content
            href: website/database_content.qmd
          - text: VegVault Access
            href: website/database_access.qmd
          - text: VegVault Structure
            href: website/database_structure.qmd
          - text: Examples of usage
            href: website/database_examples.qmd
      - text: Contribute!
        href: website/contribute.qmd
      - text: Outputs and Materials 
        href: website/materials.qmd
      - text: Get in touch!
        href: website/contact.qmd
    search: true
    repo-url: https://github.com/OndrejMottl/VegVault
    repo-actions: [source, issue]
    tools:
      - icon: bluesky
        href: https://bsky.app/profile/ondrejmottl.bsky.social
      - icon: twitter
        href: http://twitter.com/OndrejMottl
      - icon: github
        href: https://github.com/OndrejMottl/VegVault

format:
  html:
    theme: 
      - styles.scss



